### ISSUE TITLE
Fix navigation on desktop.

### ISSUE THREAD

**Issue by zberwaldt** [BanklessDAO/bankless-dao-ghost-website#100]
![image](https://user-images.githubusercontent.com/17715430/139744832-c7b588a4-108f-41cb-8320-29ec7e7e9572.png)

The "Connect Wallet" and Search icon should be aligned on the right.

**Comment by theprojectcode** [comment]
I would like to work on this issue.

**Comment by zberwaldt** [comment]
@theprojectcode this is no longer an issue. It was a local bug. apologies for the inconvenience.
