### ISSUE TITLE
Add connect a Wallet functionality.

### ISSUE THREAD

**Issue by zberwaldt** [BanklessDAO/bankless-dao-ghost-website#11]

**Comment by amaredeus** [comment]
@zberwaldt Am I able to start working?

**Comment by zberwaldt** [comment]
@amaredeus I have a few things to fix in the navbar. I'll make that priority number 1 and keep you posted.

**Comment by zberwaldt** [comment]
@amaredeus I merged my work into develop. You should be good to go. Let me know if there is anything I can do to help.

**Comment by amaredeus** [comment]
Branch created for work related to web3 connectivity. `feature/web3-wallet` https://github.com/BanklessDAO/bankless-dao-ghost-website/tree/feature/web3-wallet

**Comment by zberwaldt** [comment]
@turinglabsorg, If you need a hand with this let me know. @foxyblocks has expressed interest in pitching in on the web3 side of things if needed.

**Comment by turinglabsorg** [comment]
@zberwaldt i'm in, should i replace both top right buttons with "connect wallet"?

![Screenshot_20210828_015949](https://user-images.githubusercontent.com/14848252/131199280-f7d5cc1c-c4f7-49e2-9846-b5cb9d965e48.png)

Or there's a classic signing function? now both buttons goes nowhere..

Thanks!

**Comment by zberwaldt** [comment]
@turinglabsorg Yes, let's do that web-3 connection options should be front and center. 
Thanks for catching those links, user registration and sign-in are not set up. So, they don't have pages currently.

**Comment by turinglabsorg** [comment]
@zberwaldt i'm not sure how design will look at the and, for now i'm just commenting broken buttons, if you can leave me here the final design i will do how's supposed to be done!

**Comment by turinglabsorg** [comment]
@zberwaldt ok, i've done the final implementation here: https://github.com/BanklessDAO/bankless-dao-ghost-website/commit/7f218fb8948f5501283f2f7b469dc684e1ab1535

As you can see i've created a `web3.ts` library where all the web3 function are located. 

In the `Navbar.tsx` I've imported that library and rendered the button on top.
I've implemented yet a "remember" feature so the user will not have to click each time to connect wallet and a signup button too.

I will continue on the other opened issue, please close the issue when you've tested it, thanks.

**Comment by turinglabsorg** [comment]
![wallet_bankless](https://user-images.githubusercontent.com/14848252/131299390-fbecb1e7-de6f-4aeb-8746-1a8752b8c5d2.gif)

This is how the implementation works, it's supposed to work with WalletConnect too or we can leave the connection like that? I've seen the other website just after the implementation...let me know!

**Comment by turinglabsorg** [comment]
I think the other website uses this: https://github.com/Web3Modal/web3modal

**Comment by zberwaldt** [comment]
Awesome! It looks great. You are correct about web3Modal being used for the current site. In terms of design, It looks good to me. We can refine it moving forward.
