### ISSUE TITLE
Contribute page (used to be named Mission)

### ISSUE THREAD

**Issue by MrPackman4019** [BanklessDAO/bankless-dao-ghost-website#18]
On the demo site this appears to be a post. Also assuming this was Yves writing very early on as a sample of a Bdao mission page. https://gobankless.ghost.io/mission/

Need writers guild to write up a mission page. 

Is there actual dev work for this or is this simply a ghost admin task to create a guilds page?

**Comment by MrPackman4019** [comment]
Per the content meeting this page will be renamed to Contribute

On this page the writers guild will be drafting up a formal mission vision values as well as how to get involved.

**Comment by zberwaldt** [comment]
One of the things we could do for this is just make it a page on the admin side. Then just pull that with the content api. Then we can just create a generic template for the page.

**Comment by MrPackman4019** [comment]
@zberwaldt I think that works, Just to clarify that with my own understanding, this would give the admins a page to publish and the site would have a Contribute nav link that will go to this published page. Is that correct?

**Comment by zberwaldt** [comment]
Yea. In fact, the pages you are asking for (i.e. contribute, guilds, etc.) already exist on https://gobankless.ghost.io. I just have to pull the data for them so the pages get built. 

Moving forward, any regular page that might need to be added would just need to be authored by someone on the cms side of things.
