### ISSUE TITLE
Replicate the multisig page from the current site

### ISSUE THREAD

**Issue by MrPackman4019** [BanklessDAO/bankless-dao-ghost-website#21]
Today the dev guild set a bounty to get a multisig page up on the current bankless community page. Need to ensure this is replicated for the website refresh mvp.

- bankless.community/addresses
- Link to it is on the footer of the site.
- The current page was purely functional, may improve the aesthetics from the current page

**Comment by MrPackman4019** [comment]
May be a good idea to get with the dev that pushed this change for the current bankless dao site prior to starting this.

**Comment by jakeacooley** [comment]
@MrPackman4019 Can you give me some more details for this issue? The link `(bankless.community/addresses)` is broken and I'm not quite sure what exactly needs to be built.
