### ISSUE TITLE
Pool Together Info

### ISSUE THREAD

**Issue by amaredeus** [BanklessDAO/bankless-dao-ghost-website#23]
There is an ongoing effort to have Bankless DAO participate in Pool Together: https://forum.bankless.community/t/pooltogether-bankless-dao-pod/1331

Request is to have contracts listed in the forum proposal listed on the website.

example of product
https://sharingnotes.xyz/bankless/

**Comment by zberwaldt** [comment]
@MrPackman4019 I'm moving this to Road to V2, as I think it's out of scope for MVP. Let me know your thoughts.

**Comment by streamerd** [comment]
hey peopl, can start with this task. let me know if that's cool //
