### ISSUE TITLE
Claiming functionality:

### ISSUE THREAD

**Issue by zberwaldt** [BanklessDAO/bankless-dao-ghost-website#24]
Reference:
https://www.bankless.community/claim

**Comment by zberwaldt** [comment]
@turinglabsorg let me know if you need anything.

**Comment by turinglabsorg** [comment]
@zberwaldt is all this code (https://www.bankless.community/claim) open source? 
If not i need to understand what calls to do and where (smart contract, ABI etc), can you give me an hand?

**Comment by zberwaldt** [comment]
@turinglabsorg I'll bring this up at tonight's dev sync. I'll see if someone will spare some time as a resource for us.

Also, I merged a bunch of work into the develop branch, just want to make sure you get those changes.

**Comment by zberwaldt** [comment]
Hi. here are a couple of things that came from the meeting today.

First, for the login functionality. The general consensus is that `Web3Modal` is the way to go. 
Second, the window for the second airdrop for $BANK is closing, so it might not be worth completing. 

We'll know more tomorrow on the Website Sync (12pm EDT).

If we do continue with the claiming functionality. All the contracts for claiming are in the original websites repo:

https://github.com/BanklessDAO/bankless-dao-website

In theory, you could just grab it and plug it in on this site.

**Comment by turinglabsorg** [comment]
@zberwaldt ok, i will create a new branch and push web3modal to make the login. Good to know that we have the code already developed :muscle:

**Comment by zberwaldt** [comment]
@turinglabsorg agreed. I'll keep you posted with any new developments.

Thanks again for helping us with the project.

**Comment by wpmonty** [comment]
Claim window is closing rapidly; we will not need the Claim functionality specifically before launch, but general Web3 connectivity can continue.
