### ISSUE TITLE
Replace pure Web3 with Web3Modal

### ISSUE THREAD

**Issue by turinglabsorg** [BanklessDAO/bankless-dao-ghost-website#42]
@zberwaldt let's discuss about the replacement here, ok?

**Comment by turinglabsorg** [comment]
@zberwaldt implementation completed: https://github.com/BanklessDAO/bankless-dao-ghost-website/commit/6b90356367e882be300420d61fd615706ea5f994

You should add `NEXT_PUBLIC_INFURA_ID=18533a1dfcd146b8994f38b8e6af372c` to `.env` file. I've copied this ID from the other repository (bankless-website).

**Comment by zberwaldt** [comment]
Awesome. I'll make a pull request for this tonight.

**Comment by zberwaldt** [comment]
The connect button on mobile is not currently working. @turinglabsorg if are still available do you mind looking into this?

**Comment by turinglabsorg** [comment]
@zberwaldt of course, will check it asap

**Comment by zberwaldt** [comment]
@turinglabsorg 

Here are my thoughts: 

I think we can move the connectwallet button out of the mobile menu to its right.

![https://cdn.discordapp.com/attachments/882660031806439454/882661500215496704/image0.jpg](nav)

Another thing that I think would be really nice for mobile is to have a sticky nav. I saw this during research and I think it might be useful?

Live: https://next.jamify.org/

Code: https://github.com/styxlab/next-cms-ghost/blob/master/components/StickyNav.tsx
