### ISSUE TITLE
Mobile nav menu formatting

### ISSUE THREAD

**Issue by MrPackman4019** [BanklessDAO/bankless-dao-ghost-website#46]
In Mobile the menu is all there and aligned but the first option is highlighted as if you are hovering on it and cannot be moved and makes the option hard to read because of the color. In mobile we don't need the hover option for the menu could we remove it? Also can we make the search button the same size and coloring/format as the others menu options?

[EDIT] That search button also is not fully clickable. Right now you have to hit the search icon to make it work. Need to make it so the entire search button bar is clickable like the rest of the menu.

![Capture2](https://user-images.githubusercontent.com/83730957/131888593-2b8f64dc-e551-431a-800d-5e9dd6537a81.PNG)

**Comment by foxyblocks** [comment]
Yah I can try and squeeze this in today but i'm about to be offline for the next 4 days.  so if i disappear that's why. I'll be back on Monday 😁

**Comment by MrPackman4019** [comment]
That search button also is not fully clickable. Right now you have to hit the search icon to make it work. Need to make it so the entire search button bar is clickable like the rest of the menu.
