### ISSUE TITLE
Add pre-commit hook for type checking

### ISSUE THREAD

**Issue by foxyblocks** [BanklessDAO/bankless-dao-ghost-website#80]
The typescript codebase wide typecheck operation usually happens as part of a deploy and can cause the deploy to fail, as is what happened in #79 . We should add `yarn run tsc --noEmit` as a husky pre-commit hook so that type issues that would break the build are caught quicker.

**Comment by moshejs** [comment]
I think this is probably a larger discussion to run type checking and unit tests in CI, and be able to create deploy previews
